server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.web: debug
    org.springframework.web.client: debug
    org.springframework.boot.actuate.endpoint.web: info

management:
  endpoints:
    web:
      exposure:
        include: health, metrics